spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: archivos-api
        resources:
          limits:
            cpu: 300m
            memory: 1Gi
          requests:
            cpu: 300m
            memory: 1Gi
