apiVersion: v1
kind: Template
metadata:
  name: archivos-config-template
objects:
parameters:
- description: Application Name
  displayName: Application Name
  name: APP_NAME
  required: true
  value: entidades-api
